services:
  mysql:
    image: 'mysql:latest'
    container_name: pixelquest-db
    restart: always
    environment:
      MYSQL_DATABASE: pixel
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"